### ISSUE TITLE
Linux: compiling static libraries requires "-fPIC"

### ISSUE THREAD

**Issue by code-disaster** [floooh/fips#109]
I was trying to compile some libraries (Remotery, glsl-optimizer) on Linux Mint 64 bit. The linker complained about missing "-fPIC" compile flags.

I've added the flag to linux.cmake, but I'm not sure if using them unconditionally is the correct thing to do.

**Comment by floooh** [comment]
Thanks! I'll try to find some time to play around with it. It's strange that I didn't encounter that yet, for instance I'm linking a precompiled libcurl into Oryol.

What version of Mint is this, and gcc or clang, and what compiler version?

**Comment by code-disaster** [comment]
It's a fresh install of Linux Mint 17.3, with GCC 4.8.4 (default/latest via apt-get).

**Comment by floooh** [comment]
hmm during fips build I get an error when java is called (it's in the path and the previous steps also worked fine):
```
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['java', '-cp', '../fips-jni/fips-generators/target/fips-jnigen-jar-with-dependencies.jar', 'com.codedisaster.jnigen.JNICodeGenerator', '../../java', '../../../../build/classes/main', 'generated', '--includes', '**/gdx/graphics/*.java', '**/gdx/profiler/*.java', '**/gdx/utils/*.java']' returned non-zero exit status 255
```

I will simply try to add -fPIC to the Linux build settings and check with Oryol. The Android build also uses -fPIC so I guess it's the right thing to do. I'll write another comment when the fix is up.

**Comment by floooh** [comment]
Ok, Linux builds now generally use -fPIC: https://github.com/floooh/fips/commit/8201a23ca4fe423917eb62849a2fd83926f6e6b8, it looks like this is a requirement for building shared libs.

I also noticed that the Linux build config doesn't have any special settings for linking shared libs like the Android toolchain file (CMAKE_SHARED_LINKER_FLAGS). If you stumble over other problems this might be the reason.

Let me know if the fix works :)

**Comment by code-disaster** [comment]
Confirmed.

(The compile error you've seen is a side effect of how gdx-jnigen works - it needs the Java bytecode too, so I need to build the Java code at least once first. I always forget to do that myself.)
