### ISSUE TITLE
Platform error when using cygwin

### ISSUE THREAD

**Issue by fungos** [floooh/fips#128]
```
Traceback (most recent call last):
  File "./fips", line 8, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/home/user/Code/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/home/user/Code/fips/verbs/diag.py", line 82, in run
    check_tools(fips_dir)
  File "/home/user/Code/fips/verbs/diag.py", line 28, in check_tools
    platform = util.get_host_platform()
  File "/home/user/Code/fips/mod/util.py", line 204, in get_host_platform
    return host_platforms[platform.system()]
KeyError: 'CYGWIN_NT-6.1' 
```

What to do in this situation? At least printing a help telling to use any of the supported platforms?

**Comment by floooh** [comment]
Hmm, I haven't considered this case yet (problems with CygWin have been popping up from time to time though).

I agree, at least a proper error message is needed (as a short term solution and fallback for the future).

The other question would be what to do about cygwin, I guess the primary compiler there is gcc, so it would have to be handled as a UNIX-like platform, if this doesn't develop into an infinite rabbidhole of hacks I'm in favour of adding support for Cygwin (but first have a better error message).

I don't have my Windows laptop with me over the weekend, but I can look into this next week, or if you prefer and have time, you could also prepare a PR.
