### ISSUE TITLE
fips subprojects / header-only

### ISSUE THREAD

**Issue by thorum357** [floooh/fips#151]
Hello,

i have three things I would like to know. 

1. Is it supported to make a main fips project and multiple fips subprojects? I thought off something like the directory structure of the C++ boost libraries. 

2. Is it possible to have a normal vianilla CMake project and add a fips project to this project with add_subdirectory()?

3. Are header-only libraries supported? Or did I miss that?

Thanks for answers.

**Comment by floooh** [comment]
1. no
2. no
3. yes, see here for an example: https://github.com/floooh/sokol, and here for how to import it: https://github.com/floooh/sokol-samples

**Comment by thorum357** [comment]
Okay.

Then it seems fips isn't right tool for me. Sorry. It is a intresting project but notwhat I want.
