### ISSUE TITLE
Make Visual Studio static/dynamic runtime linking configurable.

### ISSUE THREAD

**Issue by jerett** [floooh/fips#160]
when using fips to generate VS2015 project, then run time library is always MTd type, how can I change to MDd type ?

**Comment by floooh** [comment]
Hi, that's currently hard-coded unfortunately (here: https://github.com/floooh/fips/blob/585a177d974a4b753b21a1938cfb256ac1dc718b/cmake-toolchains/windows.cmake#L78)

It would probably make sense to make this configurable through a cmake option (I'll keep this issue open to track this as a bug)

You could try an ```add_compile_options``` in the toplevel CMakeLists.txt file after the fips_setup() call as a workaround until this is fixed, but I'm not 100% sure if this works.

**Comment by jerett** [comment]
thank U !

**Comment by floooh** [comment]
Hi @jerett, can you check if the PR https://github.com/floooh/fips/pull/165 provided by @fungos does what you need?

Best way to use this is probably creating your build config in a ```fips-configs``` subdirectory of your project which adds a cmake define for FIPS_DYNAMIC_CRT, see the custom build configs in Oryol as example (e.g.: https://github.com/floooh/oryol/blob/master/fips-configs/d3d11-win64-vs2017-debug.yml).

The FIPS_DYNAMIC_CRT define would looks similar to the ORYOL_USE_D3D11 define.

**Comment by jerett** [comment]
OK, I will try it later. Thanks.
