### ISSUE TITLE
Error with emscripten and "native-wasm"

### ISSUE THREAD

**Issue by Akdez** [floooh/fips#163]
Hello.

I've got an error with configuration "webgl2-wasm-ninja":
(Platform is Windows 10 x64)

```
=== building: webgl2-wasm-ninja-release
ninja.exe -j 3 all
[0/1] Re-running CMake...
FIPS_EMSCRIPTEN_SHELL_HTML: E:/Projects/oryol/fips-sdks/win/emsdk-portable/emscripten/incoming/src/shell_minimal.html
=== fips_setup(PROJECT oryol)
CMAKE_BUILD_TYPE: Release
FIPS_ROOT_DIR: E:/Projects/oryol/fips
FIPS_PROJECT_DIR: E:/Projects/oryol/oryol
FIPS_BUILD_DIR: E:/Projects/oryol/fips-build
FIPS_DEPLOY_DIR: E:/Projects/oryol/fips-deploy
FIPS_PROJECT_NAME: oryol
FIPS_AUTO_IMPORT: ON
FIPS_CONFIG: webgl2-wasm-ninja-release
FIPS_PROJECT_BUILD_DIR: E:/Projects/oryol/fips-build/oryol/webgl2-wasm-ninja-release
FIPS_PROJECT_DEPLOY_DIR: E:/Projects/oryol/fips-deploy/oryol/webgl2-wasm-ninja-release
Host system: Windows
CMAKE_CXX_COMPILER_ID:
Detect C++ Compiler by platform: Clang (FIPS_CLANG)
FIPS_PLATFORM: EMSCRIPTEN
FIPS_PLATFORM_NAME: emsc
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Projects/oryol/fips-build/oryol/webgl2-wasm-ninja-release
[1/66] Linking CXX executable E:\Projects\oryol\fips-deploy\oryol\webgl2-wasm-ninja-release\Clear.html
FAILED: E:/Projects/oryol/fips-deploy/oryol/webgl2-wasm-ninja-release/Clear.html
cmd.exe /C "cd . && E:\Projects\oryol\fips-sdks\win\emsdk-portable\emscripten\incoming\em++.bat  --em-config E:/Projects/oryol/fips-sdks/win/emsdk-portable/.emscripten --cache E:/Projects/oryol/fips-sdks/win/emsdk-portable/.emscripten_cache  -fno-exceptions -fno-rtti -std=c++11 -stdlib=libc++ -fstrict-aliasing -Wall -Wno-multichar -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wno-long-long -Wno-overloaded-virtual -Wno-deprecated-writable-strings -Wno-unused-volatile-lvalue -Wno-inconsistent-missing-override -Wno-warn-absolute-paths -Wno-expansion-to-defined -O3 -DNDEBUG  --em-config E:/Projects/oryol/fips-sdks/win/emsdk-portable/.emscripten --cache E:/Projects/oryol/fips-sdks/win/emsdk-portable/.emscripten_cache  --memory-init-file 1 -s TOTAL_MEMORY=134217728 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s NO_EXIT_RUNTIME=1 -s USE_WEBGL2=1 -s FULL_ES3=1 -s NO_FILESYSTEM=1 -s DISABLE_EXCEPTION_CATCHING=1 -s WASM=1 -s 'BINARYEN_METHOD="native-wasm"'  --shell-file E:/Projects/oryol/fips-sdks/win/emsdk-portable/emscripten/incoming/src/shell_minimal.html -O3  --llvm-lto 1 -s OUTLINING_LIMIT=60000 --closure 0 -s ASSERTIONS=0 code\Samples\Clear\CMakeFiles\Clear.dir\Clear.cc.o  -o E:\Projects\oryol\fips-deploy\oryol\webgl2-wasm-ninja-release\Clear.html  code\Modules\Gfx\libGfx.a code\Modules\Resource\libResource.a code\Modules\Core\libCore.a && cd ."

Traceback (most recent call last):
  File "E:\Projects\oryol\fips-sdks\win\emsdk-portable\emscripten\incoming\\em++", line 16, in <module>
    emcc.run()
  File "E:\Projects\oryol\fips-sdks\win\emsdk-portable\emscripten\incoming\emcc.py", line 892, in run
    setattr(shared.Settings, key, eval(value))
  File "<string>", line 1
    native-wasm'
               ^
SyntaxError: EOL while scanning string literal
```

I don't really know what or who is wrong. I've issued this error to Emscripten tracker first: https://github.com/kripken/emscripten/issues/5743

As I've mentioned in that issue at Emscripten tracker I was able to make a small hack to fix it

**Comment by floooh** [comment]
Hi @Akdez, thanks for the report, as I wrote in the emscripten ticket, I seem to remember having seen this issue in the past. It only seems to happen on Windows, and this is not as well tested as Linux and OSX for emscripten builds.

Unfortunately it's a bit difficult to test this situation, since for the next 2.5 weeks it will be a bit hard for me to get access to a Windows machine where I can install the emscripten SDK, but I'll see if I can remember what the issue was and may be I can do some sort of "blind fix" in the meantime.

**Comment by Akdez** [comment]
Hi, @floooh. I can try to help you with testing on Windows if you want. Once you will know how it may be fixed I could try to use it.

This issue does not blocking me in any ways. I just wanted to let you know about this thing. There is no any rush in it.

**Comment by floooh** [comment]
Ok, simple removing the outer quotes doesn't work unfortunately... those strange nested quotes are somehow necessary because of the way those special args are handed to the binaryen tool, and how the emcc python script parses those :/

I've tried to reverse the quote types (now looks like this: ```-s "BINARYEN_METHOD='native-wasm'"```, in commit 240c3b9b317aa1c34adbc0caf70e652af1881d34.

Can you give it a try? It's a total shot in the air though, I doubt this fixes the issue :/

**Comment by floooh** [comment]
...I've got an idea... I'll write something in the emscripten project issue...

**Comment by Akdez** [comment]
I've took your changes and tested by building Oryol samples and webpage. They are built successfully.
Looks like `-s "BINARYEN_METHOD='native-wasm'"`  works fine. 

emcc.py got proper values:
```
key = BINARYEN_METHOD
value = 'native-wasm'
```

**Comment by floooh** [comment]
oh alright, strange but good to know :)

**Comment by floooh** [comment]
...I still have the nagging feeling that it might not work under other circumstances... I'll keep the fix in and close this issue, but will try to keep an eye on it :)
