### ISSUE TITLE
-latomic no longer works in recent GCC versions

### ISSUE THREAD

**Issue by floooh** [floooh/fips#168]
This detection and linking with libatomic no longer seems to work in recent GCC version (tested on Manjaro Linux with GCC 7.2.0 with "-static" linking):

```bash
/usr/bin/ld: cannot find -latomic
```
This is the cmake code in question:
https://github.com/floooh/fips/blob/d3ee04499b4e5edc36dc73cce096ceb7668fe0f5/cmake-toolchains/linux.cmake#L60

**Comment by pixelherodev** [comment]
Uh, this bug doesn't exist.

Correction: I just tested with GCC 8.2.0 and I can't reproduce it.

**Comment by pixelherodev** [comment]
![image](https://user-images.githubusercontent.com/10342579/46169806-0e7a0600-c26a-11e8-8e75-d346bab7478e.png)

**Comment by floooh** [comment]
Yeah, I also don't see it on my Ubuntu 18.04 laptop. Not sure in what config I saw it.
