### ISSUE TITLE
fips gen ends up in an endless loop

### ISSUE THREAD

**Issue by kaffeewolf** [floooh/fips#180]
Commit 51ce99fa3820107305fc1c2bb2ab46332115c6c9 causes fips to go into an endless loop while running gen.  
An example where it can be seen is for example:
https://github.com/gscept/fips-devil
causes fips gen to die eventually while setting up fips-libjpeg since it creates an endless directory hierarchy (on windows)

**Comment by floooh** [comment]
oh shit, sorry about that, I'll try to commit a fix ASAP

**Comment by floooh** [comment]
can reproduce on OSX...

**Comment by floooh** [comment]
Ok this should be fixed now, I reverted the broken commit.

I think what happened is that cmake is running again as long as it detects updates to .cmake files in the build directory, and the fips-imports.cmake file somehow seems to have triggered this (but only for fips-libjpeg... maybe this happens only for dependencies that create their own cmake projects, not just lib modules). The fips-imports.cmake file is now back in the project root directory, and I could no longer reproduce the infinite loop with fips-libjpeg.

Thanks a lot for the bug report!
