### ISSUE TITLE
Android has been broken (libstdc++ doesn't exist in new NDK)

### ISSUE THREAD

**Issue by pixelherodev** [floooh/fips#201]

**Comment by pixelherodev** [comment]
The way I see it, there are two main options: one, download the libstdc++ and put it in the right place manually. This would likely be easier to do short-term, but is also probably not the best idea. The second option is to reconfigure android builds to use a different standard library. I'll look into this over the next couple of days and see about creating a PR.

Not sure if I've said this elsewhere, but what you've done here is amazing, and I really appreciate this and many of your other projects. Thank you.

**Comment by floooh** [comment]
I've started to look at bit into the Android side again. First problem was that the official SDK tools don't work with the Java10 runtime, so the Java8 runtime is needed (I'll probably add a check for the right version into "./fips diag tools".

I think the proper fix is to switch to the officially supported standard library and toolchain.

I think this cmake option needs to be switched to something else:

https://github.com/floooh/fips/blob/0f5265d96478fe077eba6522a8231e506531fd16/cmake-toolchains/android.toolchain.cmake#L191

(and maybe some of the other cmake configuration option default values).
