### ISSUE TITLE
Linux release flag changes

### ISSUE THREAD

**Issue by pixelherodev** [floooh/fips#206]
Not sure if this is the right place to ask, but why were `-ffast-math` and `-ftree-vectorize` removed from the Linux release flags?

**Comment by floooh** [comment]
Several reasons:
- I'd like to minimize the number of hardwired compiler options, at least those hardwired in the 'toolchain files'
- unification with other UNIX-like platform compilation flags (e.g. OSX or emscripten don't have those flags either set by default)
- fast-math can lead to unwanted side effects, it really should be picked on a project-by-project basis
- -ftree-vectorize is enabled automatically when -O3 is used (I just wasn't aware of this yet)
