### ISSUE TITLE
`fips setup emscripten` could use precompiled binaries

### ISSUE THREAD

**Issue by rotoglup** [floooh/fips#210]
I'm a little biased as on my current Windows laptop, I run out of luck for building emscripten.

As I think troubleshooting emscripten build problems is not related to fips, that lead me to wonder if fips could setup the existing binaries instead of building ? What is the current rationale ?

Thanks :)

**Comment by floooh** [comment]
Yes I agree, we should do something about this. I had created a branch a long time ago where I played around with giving a version to ```fips setup emscripten```, so you could do ```fips setup emscripten incoming``` or ```fips setup emscripten 1.38.1``` etc... but I was hitting a problem (don't remember which one though).

It maybe better to completely change the emscripten SDK setup procedure to be a simple frontend for the "emsdk" command which would pass arguments directly through to emsdk... When I wrote the emscripten setup stuff for the first time, emsdk either didn't exist yet or didn't work properly, or didn't support to create "local" SDK installs.

A new workflow could look like this:

```
# this would just download and unpack the small emsdk archive 
> ./fips setup emsdk
# from then on, a new command 'emsdk' would be just a simple frontend, so you could do things like
> ./fips emsdk list
> ./fips emsdk update
> ./fips emsdk activate...
```
I think that sounds like a good plan.

**Comment by rotoglup** [comment]
It could be a good moment to allow emsdk sharing also ?

`fips setup sdk` could install locally but fips could rely on environment variables to use the activated emsdk ; this way, users could use their own 'system registered version' for example.

If no emsdk is activated, then perhaps fips can run an `emsdk activate latest` in the local sdk ?

**Comment by rotoglup** [comment]
Since I opened the issue, I've been hacking fips to use a binary installation without much trouble.

I had to change `cmake-toolchains/emscripten.toolchain.cmake` to use environment variables to check/find the activated emsdk ; something like :

```diff
--- a/cmake-toolchains/emscripten.toolchain.cmake
+++ b/cmake-toolchains/emscripten.toolchain.cmake
@@ -15,8 +15,9 @@
 
 # define emscripten SDK version
- set(FIPS_EMSCRIPTEN_SDK_VERSION "incoming")
 if (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Windows")
-    set(EMSC_EMSDK_DIRNAME "../fips-sdks/win/emsdk-portable/emscripten/${FIPS_EMSCRIPTEN_SDK_VERSION}")
+    set(EMSC_EMSDK_DIRNAME $ENV{EMSCRIPTEN})
 elseif (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin")
     set(EMSC_EMSDK_DIRNAME "../fips-sdks/osx/emsdk-portable/emscripten/${FIPS_EMSCRIPTEN_SDK_VERSION}")
 elseif (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Linux")
@@ -27,15 +28,15 @@ endif()
 macro(find_emscripten_sdk)
     # first check for the official EMSDK, this does not allow to override
     # the location of the .emscripten config file
-    get_filename_component(EMSCRIPTEN_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/../${EMSC_EMSDK_DIRNAME}" ABSOLUTE)
+    get_filename_component(EMSCRIPTEN_ROOT_PATH $ENV{EMSCRIPTEN} ABSOLUTE)
     if (NOT EXISTS "${EMSCRIPTEN_ROOT_PATH}/emcc")
-        message(FATAL_ERROR "Could not find emscripten SDK! Please run 'fips setup emscripten'!")
+        message(FATAL_ERROR "Could not find emscripten SDK in '${EMSCRIPTEN_ROOT_PATH}/emcc'! Please run 'fips setup emscripten'!")
     endif()
 endmacro()
 
 # find the emscripten SDK
 find_emscripten_sdk()
-set(EMSCRIPTEN_LLVM_ROOT "${EMSCRIPTEN_ROOT_PATH}/../../clang/fastcomp/build_${FIPS_EMSCRIPTEN_SDK_VERSION}_64/bin")
+set(EMSCRIPTEN_LLVM_ROOT $ENV{LLVM_ROOT})
```

I think the `check_exists` function in `mod/emscripten.py` could also check the environment variables.

**Comment by floooh** [comment]
Yes it would be a good opportunity to (optionally) use the globally installed emscripten SDK. I just don't want this as the only option, since a local SDK which doesn't "pollute" anything outside it's fips workspace is handy as well.

**Comment by rotoglup** [comment]
Ok, I guess I can try to draft the changes in a PR, would that be OK for you ?

I only have access to a Windows system, would you be able to check on Linux/Mac ?

**Comment by floooh** [comment]
Yes, a PR would be welcome (for the alternative emsdk install, the environment variable things above should at most be optional for the "use globally installed SDK" base, the "use locally installed SDK" should not depend on any environment variables).

I think it's best to keep the current emscripten.py as it is for now, and put everything into a new "emsdk.py" fips verb (with the goal to deprecate the "fips setup" verb long-term, and instead use "fips emsdk setup" and "fips android setup").

**Comment by rotoglup** [comment]
Hi,

I've started a branch in https://github.com/rotoglup/fips/commits/emsdk-verb, 

So far, I've added an `emsdk` verb that relays commands to the local emsdk script when installed, and a `setup` command that downloads, installs and activate the `latest` sdk version.

For the cmake toolchain part, I've changed the existing file to use `EM_CONFIG` and `EMSCRIPTEN` environment variables for now.

While trying to figure how to detect / use which emscripten version is setup by `latest`, I come to think that fips should use the proper emsdk environment (variables) to build.

For example, the `EM_CACHE` environment variable seems to exist specifically for embedded uses of the SDK (from the comments in https://github.com/kripken/emscripten/pull/3491).

Thinks brings me to the following questions : 

* Would you prefer discuss further in a PR or it this issue ? :)
* Would you mind if a fips user had to 'activate' the emscripten environment before using it ? say with a `fips emsdk setenv` command ? I think this would make things simple and explicit (with the proper error messages), and also 'solve' priority questions between a local emsdk and an activated one.

**Comment by floooh** [comment]
Hi apologies for replying so late, I went a bit into hermit mode over my Christmas vacation :)

Ok:

- yes, I think it makes sense to move further discussion into a PR
- the EM_CACHE variable is a bit chicken/egg-like. I'd prefer to not depend (or set) any environment variables at all, since these mess with the user's global environment. It should be possible to have several emsdk installation at different activated versions side by side. The ```emcc.py``` script basically overwrites the EM_CACHE variable anyway here with the ```--cache``` cmdline arg (that's what fips does when it invokes emcc): https://github.com/kripken/emscripten/blob/04fef5b48c3cefb0f9001e6d9daca9380838b335/emcc.py#L2265-L2270
- we should try making the SDK work without setting an explicit version after installation, for instance:
  - find out what the latest stable version by looking at the output of ```emsdk list```
  - or have a hardwired "known good version" in fips, which we bump from time to 

...other then that I was hoping that we can simply forward the fips cmdline args to emsdk, e.g.:

```
> ./fips emsdk update
...
> ./fips emsdk list
...
> ./fips emsdk activate ...
```
...the ```activate``` command should always add an ```--embedded``` though I guess...

**Comment by rotoglup** [comment]
Hi, no problem :) I have to reconnect myself to this issue/PR though, I'll start by creating a PR ASAP

**Comment by floooh** [comment]
...btw I have started working on this now, totally forgot about this ticket, I hope you haven't put too much work into it.

The main motivation was that the emscripten SDK will soon switch to the new LLVM backend, and with this come changes in the SDK directory structure, so I'll have to rewrite the whole emscripten SDK handling anyway.

This also fixes a long-standing problem where the cmake toolchain file is hardwired to a specific emscripten SDK path, this will now all be handled correctly.

Work happens here: https://github.com/floooh/fips/pull/225

**Comment by rotoglup** [comment]
Hi,

Ok great, thanks for the info, and no worries, it was interesting to peek
at fips code :) sorry I couldn't help that much.

Cheers,
N

Le sam. 25 mai 2019 à 16:54, Andre Weissflog <notifications@github.com> a
écrit :

**Comment by floooh** [comment]
This has now been merged.
