### ISSUE TITLE
Producing a compile_commands.json

### ISSUE THREAD

**Issue by shanemikel** [floooh/fips#212]
I'm wondering how I might use this system together with Bear (or producing the compile_commands.json file with CMake directly).

It's basically a file that tells where the includes for a project are so that IDEs and code editors can provide completion and other features.

**Comment by shanemikel** [comment]
Usually I use hand written Makefiles, and the Bear tool is run like so:
`# bear make -B`

The -B flag forces a complete build, and the Bear program parses the output of Make to build a structured JSON file enumerating the included files for each output.

**Comment by floooh** [comment]
...wait there's a problem, CMAKE_EXPORT_COMPILE_COMMANDS is only implemented by the ninja generator:

https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html

I need to add a fix back in which only sets the define when the ninja generator is used...

**Comment by floooh** [comment]
Ok, fix is in https://github.com/floooh/fips/commit/274d0ff26dc0530e5618376673de031ba7ab658f

**Comment by smokku** [comment]
Why was this feature removed in 9512fb6d0e99322a2e2366f4e7eb13a643ca0d07 ?

**Comment by floooh** [comment]
Hmm, probably fallout from the changes to write a CMakePresets.json, but not sure if this broke compile_commands.json or I thought that compile_commands.json would no longer be needed since IDEs use the CMakePresets.json file to figure out the information that's been written to compile_commands.json previously.

It may also be that having both a compile_commands.json and CMakePresets.json file confused the VSCode CMake Tools extension.

What's your use case for the compile_commands.json file?

**Comment by smokku** [comment]
> What's your use case for the compile_commands.json file?

I use [`clangd`](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension for context help and error detection.

![image](https://github.com/floooh/fips/assets/147687/a06b5b1a-582e-4155-984f-dab664db1476)

It needs `compile_commands.json` to properly analyze the code.

**Comment by smokku** [comment]
BTW, I am able to run `./fips config` then `[t] Toggle advanced mode` and enable `CMAKE_EXPORT_COMPILE_COMMANDS    ON` there.

But it would be nice if I would not have to. :-)

**Comment by floooh** [comment]
FYI I reverted that change again in https://github.com/floooh/fips/commit/ae37991693ffbd8bb4b05e75abed203a98299621, so `compile_commands.json` is generated again. I only did some quick testing in VSCode on Mac and didn't see any problems, so either if there are problems, they are more subtle than what I'm currently seeing, or I really thought that the feature wasn't needed anymore when I removed it.

**Comment by smokku** [comment]
Works fine! Thanks.

I just need to create `.clangd` config file in the root of my project, to point clangd to out-of-source compilation database and I'm done.

```
> cat .clangd

CompileFlags:
  CompilationDatabase: ../fips-build/tech42/linux-ninja-debug
```
