### ISSUE TITLE
fips run app: working dir is not the same on windows and macOS

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/fips#220]
When you run "fips run app" on windows the working directory is the project folder, but on macOS it's the deploy-dir.

Is there a way to set the working dir in fips?

I guess my follow up question is: what's the fips way to handle resources/assets getting copied over to the deploy-dir? Using cmake to copy them over? 

Only getting started with fips with a new project, so maybe I've missed something. Thanks for a great project!

**Comment by mattiasljungstrom** [comment]
Not sure what I did wrong yesterday, but now my working dir is fips-deploy on windows as well. :)

**Comment by floooh** [comment]
The working directory isn't really defined anywhere, but I have defined various cmake variables to the interesting filesystem locations. When you run ```./fips gen``` you'll see things like this:

```
FIPS_PROJECT_DIR: /Users/floh/projects/sokol-tools
FIPS_BUILD_DIR: /Users/floh/projects/fips-build
FIPS_DEPLOY_DIR: /Users/floh/projects/fips-deploy
...
FIPS_PROJECT_BUILD_DIR: /Users/floh/projects/fips-build/sokol-tools/osx-xcode-debug
FIPS_PROJECT_DEPLOY_DIR: /Users/floh/projects/fips-deploy/sokol-tools/osx-xcode-debug
```
...I think ```FIPS_PROJECT_DEPLOY_DIR``` is what you want.

For asset copying, I passed those cmake variables when invoking python "generator scripts" (which are not only useful for code-generation as the name implies, but also for general asset-pipeline tasks).

For instance here's a cmake-macro which passes the FIPS_PROJECT_DEPLOY_DIR and FIPS_PROJECT_BUILD_DIR cmake variables to a python generator-script:

```cmake
macro(n3h5_textures yml_file)
    fips_generate(FROM ${yml_file}
        TYPE texconv
        OUT_OF_SOURCE
        ARGS "{ deploy_dir: \"${FIPS_PROJECT_DEPLOY_DIR}\", build_dir: \"${FIPS_PROJECT_BUILD_DIR}\" }")
endmacro()
```
...and in the python script, you can access those like this:

```python
# the 'generate' function is called by fips
def generate(input, out_src, out_hdr, args):
    ...
    build_dir = args['build_dir'] + '/'
    deploy_dir = args['deploy_dir'] + '/'
    ...
```

**Comment by floooh** [comment]
PS: the Oryol shader compiler system uses a similar macro, but not with the directory variables:

https://github.com/floooh/oryol/blob/043683dcb3181beb64ae1c85ea76e4a4eb71c124/fips-files/include.cmake#L194-L204

This is then used like this to add a shader-compilation build-task:
https://github.com/floooh/oryol/blob/043683dcb3181beb64ae1c85ea76e4a4eb71c124/code/Samples/Shapes/CMakeLists.txt#L4

...which during a build calls this python "generator-function":

https://github.com/floooh/oryol/blob/043683dcb3181beb64ae1c85ea76e4a4eb71c124/fips-files/generators/Shader.py#L673

**Comment by mattiasljungstrom** [comment]
Thanks, this is what I was looking for!
