### ISSUE TITLE
A "fips-libs/fips-asset-utils" project would be useful...

### ISSUE THREAD

**Issue by floooh** [floooh/fips#221]
This could contain generally useful generator-script, for instance:

- copy asset files from project directory into the deploy directory
- convert a binary file into an embedded C array
- texture conversion(?)
- sprite-atlas generator(?)
...

**Comment by fabiopolimeni** [comment]
So, I was just looking for a solution to the first point of your list.

What would you say is the best way to solve this, in a *fips* way?
Would I need to write a *fips generator*?

**Comment by floooh** [comment]
If the files should be copied during the build process, then a generator is the way to go.

Here's an example which takes a yaml file with a list of files to copy as input, and copies those files into the project's deployment directory (where the executables are places):

https://gist.github.com/floooh/692efeb3abe65ee0b7c8108ec0d6ac9f

The filecopy.py file is the important part, this would go into the ```fips-files/generators``` directory. 

The cmake macro could be put into ```fips-files/include.cmake``` to make the macro available for other projects.

**Comment by fabiopolimeni** [comment]
Great! Thanks, this is super useful ;)

**Comment by kochol** [comment]
> convert a binary file into an embedded C array
I was thinking about doing this for my textures but then find out it is not a good solution for a game as it gets memory on RAM for them but I only need them on VRAM.

**Comment by kochol** [comment]
> 
> 
> If the files should be copied during the build process, then a generator is the way to go.
> 
> Here's an example which takes a yaml file with a list of files to copy as input, and copies those files into the project's deployment directory (where the executables are places):
> 
> https://gist.github.com/floooh/692efeb3abe65ee0b7c8108ec0d6ac9f
> 
> The filecopy.py file is the important part, this would go into the `fips-files/generators` directory.
> 
> The cmake macro could be put into `fips-files/include.cmake` to make the macro available for other projects.

What about the apk files? How can I add them to my apk files?

**Comment by kochol** [comment]
I added some code to android-create-apk.py that add assets folder to the APK if the folder exists and sync my assets folder with a fips generator. 
Also, I will change a Version number in my cpp file to force the fips to create the apk again.

The code is here: https://github.com/kochol/ari2/blob/master/fips-files/generators/Assets.py

What do you think about this approach?
I will create a pull request

**Comment by floooh** [comment]
PSA: I have created a "fips-utils" repository here for "generally useful stuff that shouldn't live in the core repository". I'll start to move and unify scripts and "non-core-features" from the fips repo there over the next days:

https://github.com/fips-libs/fips-utils
