### ISSUE TITLE
osx-vscode-release builds with -O0 instead of -O3

### ISSUE THREAD

**Issue by lawsonfulton** [floooh/fips#237]
Hi there,

Great tool you've built here! I'm still very much learning how to use it, but I've encountered some strange behaviour.

When I do `./fips build osx-vscode-release` it seems to compile with debug flags rather than release.

This doesn't appear to happen with any other osx configs such as make or xcode.

Let me know if their is any more info I can provide that would help!

**Comment by floooh** [comment]
Hi, that would indeed be strange, can you provide steps to reproduce the problem? Doing a quick check compiling on the command it seems to work as expected (with osx-vscode-release and osx-make-release), both produce identical executables:

<img width="654" alt="Screen Shot 2019-08-10 at 12 38 34 PM" src="https://user-images.githubusercontent.com/1699414/62820890-8d6aeb00-bb6b-11e9-9e65-0cb5e92d9211.png">

However, it is possible to override the original build config files in the project, or dependencies, this type of bug can happen when ```osx-vscode-release``` has been overridden in a project, but the ```build_type=Release``` hasn't been set in the config file.

Can you do a ```./fips list configs``` in your project directory and post the list here? This should show where the ```osx-vscode-release``` config is taken from.
