### ISSUE TITLE
optional imports still fetch git repository?

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/fips#241]
I've been trying to get the fips-imgui (https://github.com/fips-libs/fips-imgui) to not download the glfw dependency. But I've failed setting this up so far. 

Is there any way to do this? The condition flag seems to only remove including it in the build, but the repository is still downloaded. Or have I missed something?

**Comment by floooh** [comment]
Yeah, the 'cond' field only controls inclusion of the dependency into the project, not whether it's actually fetched. The whole dependency import is already quite complex, and I hesitate a bit changing it's behaviour ;)

**Comment by floooh** [comment]
...ah ok, and now I also remember *why*: that condition string in the 'cond' key in fips.yml is actually a CMake script snippet. Fetching the dependencies is done through python though. The whole feature isn't thought out that well TBH...

**Comment by mattiasljungstrom** [comment]
Ok, thanks for the info! I guess I will stay with current setup or make my own clone of imgui without the import.
