### ISSUE TITLE
MSVC treat warnings as errors

### ISSUE THREAD

**Issue by davreev** [floooh/fips#253]
When building on Windows, it looks like "treat warnings as errors" is enabled even after removing the `/WX` flags in the top level `CMakeLists.txt` file via

```
if (FIPS_MSVC)
    string(REPLACE "/WX " "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}") 
    string(REPLACE "/WX " "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
endif()
```
Not entirely sure if this is a fips issue but ideally it could be enabled/disabled on a per target basis with a function call (similar to `fips_vs_warning_level`).

**Comment by davreev** [comment]
Not entirely sure if this is a fips issue but ideally it'd be nice to be able to enable/disable this on a per target basis with a function call (similar to `fips_vs_warning_level`).

**Comment by davreev** [comment]
Also worth noting that this is still the case after removing `/WX` from `cmake-toolchains/windows.cmake` directly.

**Comment by davreev** [comment]
Was able to get it to work by making the following change to `fips_vs_apply_options`:

```
macro(fips_vs_apply_options target)
    if (FIPS_MSVC)
        if (NOT ${CurCompileFlags} STREQUAL "")
            # set_target_properties(${target} PROPERTIES COMPILE_FLAGS ${CurCompileFlags}) # This doesn't pick up /WX-
            set_target_properties(${target} PROPERTIES COMPILE_DEFINITIONS ${CurCompileFlags}) # This does
            message("\n\nCOMPILE DEFS SET\n\n")
        endif()

        # set the deploy-directory as the debugger working directory
        set_target_properties(${target} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY ${FIPS_PROJECT_DEPLOY_DIR})
    endif()
endmacro()
```
For some reason, `/WX-` will be picked up if set to [`COMPILE_DEFINITIONS'](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_DEFINITIONS.html) instead of [`COMPILE_FLAGS`](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_FLAGS.html). Looking at the docs, it's not very clear why one would work over the other in this case.

**Comment by floooh** [comment]
Thanks for the bug report. Yeah, currently I generally have warnings as errors hardwired on MSVC along with a number of other things, that's a bit of a left-over from my older cmake-wrapper projects.

For other global settings like RTTI or C++ exceptions, there are cmake option variables (which could either be controlled from the build-config yml file, or set at the top of the root CMakeLists.txt file). I think it would make sense to more options for other currently hardwired behaviour, like warnings-as-errors.

**Comment by floooh** [comment]
FYI, I just changed the behaviour so that warnings are only treated as errors on MSVC when compiling for Release mode. In Debug mode, warnings are no longer treated as errors.
