### ISSUE TITLE
LNK203 _MSC_VER

### ISSUE THREAD

**Issue by H4ZY** [floooh/fips#257]
I am trying to build FBXC but I am getting this 
"error LNK 2038 mismatch detected for '_msc_ver' value '1800' doesn't match value '1900''

Full error code
https://pastebin.com/KJ6RWsZu

**Comment by floooh** [comment]
Looks like this is a Visual Studio version mismatch between your installed Visual Studio version and the precompiled libraries in the FBX SDK (or whatever SDK libfbxsdk-mt.lib is part of). I don't think this is fips specific, instead you need to use the FBX SDK which matches your Visual Studio version (from the FBX download page it looks like only VS2012, 2013 and 2015 is supported).

**Comment by floooh** [comment]
PS: https://github.com/floooh/fbxc was more like an experiment and is no longer support, I would suggest using assimp (https://www.assimp.org/) for loading and processing FBX files.
