### ISSUE TITLE
Moving Directories

### ISSUE THREAD

**Issue by frink** [floooh/fips#264]
I moved all my fips stuff from `~/*` to `~/floooh/` in the process this broke all my builds. Apparently, fips is fairly brittle and opinionated about its directory layout...

**Comment by floooh** [comment]
...did you run 'fips clean all' afterwards before attempting to rebuild? Cmake generates tons of absolute paths in its intermediate build files, and there also other places where *generated* files contain absolute paths. But all those should be wiped and recreated after a 'fips clean all' followed by a 'fips gen'.

When run from a clean slate, fips itself shouldn't depend on any absolute paths, everything is relative to the current project's root direcory.

**Comment by frink** [comment]
> ...did you run 'fips clean all' afterwards before attempting to rebuild?

nope... Thanks for letting me know.

> Cmake generates tons of absolute paths in its intermediate build files, and there are also other places where generated files contain absolute paths.

Yet one more reason to hate CMake or anything that depends on it...

Thanks for letting me know. I'll close this one...
