### ISSUE TITLE
android SDK changed the folder tree

### ISSUE THREAD

**Issue by kochol** [floooh/fips#268]
New fips setup android downloads a version of android SDK that the folder trees are different from previous one so fips build is not working for android

**Comment by floooh** [comment]
Yeah, I noticed this while on my vacation. I need to look into this soon because right now I have removed the Android build from the sokol-sample CI builds.

**Comment by floooh** [comment]
...the curious thing is that fips hasn't changed anything, the Android SDK installer that fips downloads suddenly broke from one day to the other. Not really surprising, because the Android SDK tend to break, but that a breakage is "backported" to old SDKs is a new one I think ;)

**Comment by kochol** [comment]
Maybe its better to host the android SDK ourselves

**Comment by floooh** [comment]
Ok, I have updated the cmake toolchain file in fips with the file from the Android NDK, which also fixes this path problem. Builds tested in the sokol-samples repository.
