### ISSUE TITLE
direct ccache support

### ISSUE THREAD

**Issue by mgerhardy** [floooh/fips#27]
It should be cool if you could get ccache support out of the box and not fiddle around with env vars.

**Comment by floooh** [comment]
haven't used ccache yet but sounds like a useful feature to have

**Comment by floooh** [comment]
Fixed in 78b25c3cb0eb312c16f7cbebdfc5d3647be66fad, activated via './fips set ccache on', only tested on OSX so far, and ccache doesn't seem to work when compiling for emscripten, so I disabled it there.
