### ISSUE TITLE
Add support for building with multiple cores

### ISSUE THREAD

**Issue by mgerhardy** [floooh/fips#31]
at least the unix makefile project could make use of this - maybe as an env var, or cmake set, or ....

**Comment by floooh** [comment]
Currently this is hardwired to 3 jobs for make, ninja and xcodebuild (when building though cmake this unfortunately doesn't allow to tweak number of jobs). I think configuring this through a setting is the best way ('fips set jobs 8').

**Comment by floooh** [comment]
Hmm, looks like the 'make -jN' wasn't actually using multiple cores, only after I removed the 'shell=True' from the python subprocess.call()

**Comment by floooh** [comment]
Ok, this should be fixed in bcbd430e8183cb5cddb4c7af496dc01b58323fe4, use './fips set jobs N' to configure, should work for make, ninja and xcodebuild, building for cmake (e.g. VStudio projects) doesn't have a way to configure number of jobs unfortunately.
