### ISSUE TITLE
fips_unittests.cmake: remove Oryol specific code

### ISSUE THREAD

**Issue by floooh** [floooh/fips#32]
The generated main.cc file for a UnitTest has Oryol-specific calls in it: https://github.com/floooh/fips/blob/master/cmake/fips_unittests.cmake#L44, this should be replaced with a project-specific template file (and if the project doesn't provide a template file, use a generic file).

Probably use cmake's configure_file for this: http://www.cmake.org/cmake/help/v3.1/command/configure_file.html

**Comment by mgerhardy** [comment]
btw, the same is true for the plist templates. Should go into MacOSX.plist.in and configure_file should be used here, too

(sorry for hijacking this issue)

**Comment by floooh** [comment]
Oryol dependency of unittest code has been removed (without configure_file, this would have been overly complex.
