### ISSUE TITLE
Make warning level configurable (./fips set warn [warn-level])

### ISSUE THREAD

**Issue by floooh** [floooh/fips#35]
The global warning level for compiling should be configurable (3 or 4 warning levels).

**Comment by code-disaster** [comment]
FYI these are the warnings I currently disable globally for /Wall. There are of course more, arguable ones, like "warn about unused variable/parameter" which is disabled for OS X & Linux by fips.

```
        /wd4255         # 'function' : no function prototype given: converting '()' to '(void)'
        /wd4514         # 'function' : unreferenced inline function has been removed
        /wd4711         # function 'function' selected for inline expansion
        /wd4820         # 'bytes' bytes padding added after construct 'member_name'
```

In addition I wrap Windows headers with:

```
#pragma warning(push, 3)
#include <...>
#pragma warning(pop, 3)
```

**Comment by floooh** [comment]
Reminder to self: it might actually be better to set the warning level as cmake statement fips_warning_level(x), in a way that it would spread to all CMakeLists files below the current... this would allow better fine-tuning for libs...

**Comment by floooh** [comment]
The concept of 'warning level' is VStudio compiler specific, I have implemented a macro 'fips_vs_warning_level(x)' a while ago, where x is the VStudio warning level. This can be set inside a begin_xxx()/end_xxx() module definition and only applies to that module.
