### ISSUE TITLE
Compiler detection can cause CMake warning

### ISSUE THREAD

**Issue by code-disaster** [floooh/fips#52]
The new detection macro (FIPS_MSVC et al) seems to not work with some combinations - in my case, CMake 3.1.1 and MSVC 2013 Community Edition. The compiler define isn't set, and this warning is written to the console:

```
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
```

The fix is to change this to the following, though I'm not sure how compatible this is with other OS'es and/or older CMake versions:

```
    # detect compiler
    if (${CMAKE_CXX_COMPILER_ID} STREQUAL Clang)
        set(FIPS_CLANG 1)
        message("C++ Compiler: Clang (FIPS_CLANG)")
    elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL GNU)
        set(FIPS_GCC 1)
        message("C++ Compiler: GCC (FIPS_GCC)")
    elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
        set(FIPS_MSVC 1)
        message("C++ Compiler: VStudio (FIPS_MSVC)")
    else()
        message("C++ Compiler: Unknown")
    endif()
```

**Comment by floooh** [comment]
I'll try your fix on my Windows setup with cmake 2.8.12, if it works I'll commit a fix.

**Comment by floooh** [comment]
Cmake is weird. This happens because MSVC itself is a pre-defined CMake variable. I changed the MSVC detection to simply check for this variable now. Tested with latest cmake on Windows and OSX, and I will also do a quick check on Linux Mint 17 (Debian based).

**Comment by floooh** [comment]
Also tested on Linux (but with a fairly ancient cmake version of 1.8.12)
