### ISSUE TITLE
Can't build when there is not imports.

### ISSUE THREAD

**Issue by fungos** [floooh/fips#78]
When trying to get fips-bgfx to build I've got an error caused by this:

https://github.com/floooh/fips/blob/master/mod/dep.py#L370-371

Removing this I can generate the project and build without problems.
I would do a PR, but I'm not sure about the fix, still learning fips :)

**Comment by floooh** [comment]
Good catch, that bug must be a side effect of another recent change. Removing the error message would not be the proper fix :) I'll try to look into this in the evening (also into the pull request). I should also add a test case for this to .travis.yml.

**Comment by floooh** [comment]
Looks like an empty dictionary also evaluates to False, but is not None. Makes sense in a way...

**Comment by fungos** [comment]
Interesting.
Thanks for the fix.
