### ISSUE TITLE
Disable eclipse linked resources

### ISSUE THREAD

**Issue by mgerhardy** [floooh/fips#97]
It produces a lot of problems in eclipse to show the linked resources. This duplicates the indexer, the reference resolving and even the searching:

It would have done a pull request - but I don't know where to put this.

SET(CMAKE_ECLIPSE_GENERATE_LINKED_RESOURCES OFF)

**Comment by floooh** [comment]
If this doesn't have any side-effect when not using Eclipse, then inside fips_setup() in cmake/fips.cmake would be a good place.
